name: Fix
on:
  workflow_dispatch:
jobs:
   changes: # Job that list subdirectories
        runs-on: ubuntu-latest
        name: Check code changes
        outputs:
            dirs: ${{ steps.filter.outputs.changes }}
        steps:
            - uses: actions/checkout@v3
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                list-files: shell
                filters: |
                  text:
                    - 'text/**/*'
   build-deploy-Prod:
        if: ${{ needs.changes.outputs.dirs != '[]' }}
        runs-on: ubuntu-latest
        needs: changes
        strategy:
            matrix:
              dir: ${{ fromJSON(needs.changes.outputs.dirs) }} # List matrix strategy from directories dynamically
        steps:
            - uses: actions/checkout@v3
