name: Fix
on:
  workflow_dispatch:
jobs:
    release:
        runs-on: ubuntu-latest
        name: create a release
        steps:
         - uses: actions/checkout@v3
         - name: Create a GitHub release
           uses: ncipollo/release-action@v1
           with:
            tag: v1.1
            prerelease: true
            makeLatest: true
            generateReleaseNotes: true
           
   # changes: # Job that list subdirectories
   #      runs-on: ubuntu-latest
   #      name: Check code changes
   #      outputs:
   #          dirs: ${{ steps.filter.outputs.changes }}
   #      steps:
   #          - uses: actions/checkout@v3
   #          - uses: dorny/paths-filter@v2
   #            id: filter
   #            with:
   #              list-files: shell
   #              filters: |
   #                text:
   #                  - 'texta/*'
   # build-deploy-Prod:
   #      if: ${{ needs.changes.outputs.dirs != '[]' }}
   #      runs-on: ubuntu-latest
   #      needs: changes
   #      strategy:
   #          matrix:
   #            dir: ${{ fromJSON(needs.changes.outputs.dirs) }} # List matrix strategy from directories dynamically
   #      steps:
   #          - uses: actions/checkout@v3
