name: Fix
on:
  workflow_dispatch:
jobs:
   changes: # Job that list subdirectories
        runs-on: ubuntu-latest
        name: Check code changes
        outputs:
            dirs: ${{ steps.filter.outputs.changes }}
        steps:
            - uses: actions/checkout@v3
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                list-files: shell
                filters: |
                  currency-rates-population-lambda:
                    - 'currency-rates-population-lambda/**/*'
                  events-publisher:
                    - 'events-publisher/**/*'
                  mailer:
                    - 'mailer/**/*'
                  max-mind-importer:
                    - 'max-mind-importer/**/*'
                  orders-reslover:
                    - 'orders-reslover/**/*'
                  publisher-award-mock:
                    - 'publisher-award-mock/**/*'
                  publisher-login-mock:
                    - 'publisher-login-mock/**/*'
                  publisher-player-info-sync-mock:
                    - 'publisher-player-info-sync-mock/**/*'
                  stripe-webhooks:
                    - 'stripe-webhooks/**/*'
                  support-mailer:
                    - 'support-mailer/**/*'
   build-deploy-Prod:
        if: ${{ needs.changes.outputs.dirs != '[]' }}
        runs-on: ubuntu-latest
        needs: changes
        strategy:
            matrix:
              dir: ${{ fromJSON(needs.changes.outputs.dirs) }} # List matrix strategy from directories dynamically
        steps:
            - uses: actions/checkout@v3
